version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/repo

jobs:
  pre:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test
      - run: npm run test:cov
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run prebuild
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm publish --access public

workflows:
  build-test-publish:
    jobs:
      - pre:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master
      - test:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master
          requires:
            - pre
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master
          requires:
            - test
      - publish:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - build